# To create an env based on this file, run the command
#   conda env create --name <env_name> --file=environment.yml
name: hotspice310
channels:
  - defaults
dependencies:
  - python=3.10.4
  - conda-forge::cupy=10.6.0
  - numpy=1.21.5
  - scipy=1.7.3
  - pandas=1.4.1
  - statsmodels=0.13.2
  - joblib=1.1.0
  - psutil=5.9.0
  - matplotlib=3.5.1
  - ipython=8.2.0
  - colorama=0.4.4
  - pylint=2.12.2
